---
- hosts: localhost
  gather_facts: False

  vars:
    region: ap-south-1
    instance_type: t2.micro
    ami: ami-5b673c34
    keypair: awsdemo

  tasks:
    - name: Create New EC2 Instance
      ec2:
        key_name: "{{ keypair }}"
        aws_access_key: "{{ aws_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        group: launch-wizard-1 #Security Group Name
        instance_type: "{{ instance_type }}"
        image: "{{ ami }}"
        wait: True
        region: "{{ region }}"
        count: 1
        count_tag:
          Name: "Demo"
        instance_tags:
          Name: "Demo"
        vpc_subnet_id: "subnet-550f5e3d"
        assign_public_ip: yes
      register: ec2

    - name: Print ec2 module output
      debug: var=ec2

    - debug:
        msg: "{{ item['private_ip'] }}"
      with_items: "{{ ec2.instances }}"
  
    - set_fact: ip_list= "[]"
    
    - name: Construct IP List
      set_fact: ip_list= "{{ ip_list }} + ['{{ item.private_ip }}']"
      with_items: "{{ ec2.instances }}"

    - name: Print IP List
      debug: msg= "{{ ip_list }}" 
        #msg: "{{ ip_list }}"
